OPERATIONS = { '+' => { :arguments => 2, :inline => true,
                        :precedence => 1,
                        :order => "left",
                        :associative => true,
                        :numeric => lambda do |x,y| x+y end },
               '-' => { :arguments => 2, :inline => true,
                        :precedence => 1,
                        :order => "left",
                        :associative => false,
                        :numeric => lambda do |x,y| x-y end },
               '*' => { :arguments => 2, :inline => true,
                        :precedence => 2,
                        :order => "left",
                        :associative => true,
                        :numeric => lambda do |x,y| x*y end },
               '/' => { :arguments => 2, :inline => true,
                        :precedence => 2,
                        :order => "left",
                        :associative => false,
                        :numeric => lambda do |x,y| x.quo(y) end },
               '^' => { :arguments => 2, :inline => true,
                        :precedence => 3,
                        :order => "right",
                        :associative => false,
                        :numeric => lambda do |x,y| x**y end },
               '|' => { :arguments => 3, :inline => true,
                        :separator => ["="],
                        :precedence => 0,
                        :order => "left",
                        :associative => false },
               'sin'=>{ :arguments => 1,
                        :numeric => lambda {|x| Math.sin(x)} },
               'cos'=>{ :arguments => 1,
                        :numeric => lambda {|x| Math.cos(x)} },
               'tan'=>{ :arguments => 1,
                        :numeric => lambda {|x| Math.tan(x)} },
               'arcsin' => { :arguments => 1,
                             :numeric => lambda {|x| Math.asin(x)} },
               'arccos' => { :arguments => 1,
                             :numeric => lambda {|x| Math.acos(x)} },
               'arctan' => { :arguments => 1,
                             :numeric => lambda {|x| Math.atan(x)} },
               'exp' => { :arguments => 1,
                          :numeric => lambda {|x| Math.exp(x)} },
               'ln' => { :arguments => 1,
                         :numeric => lambda {|x| Math.log(x)} },
               'u' => { :arguments => 1,
                        :numeric => lambda {|x| -x} },
               'log' => { :arguments => 2,
                          :numeric => lambda {|x,y| Math.log(y,x)} },
               'N' => { :arguments => 1,
                        :numeric => lambda {|x| x * 1.0 } },
               'D' => { :arguments => 2 } }
